create database hospital;
use hospital;


-- HOSPITAL MANAGEMENT SQL DATA ANALYSIS PROJECT
-- Name: C.A.Arifa
-- Tool: MySQL Workbench 8.0



-- PROJECT OVERVIEW

-- This project analyzes hospital data to generate insights
-- related to patient visits, revenue, doctor performance,
-- and treatment demand using SQL.



-- DATASET TABLES USED

-- 1. patients
-- 2. doctors
-- 3. appointments
-- 4. treatments
-- 5. billing



show tables;

DESCRIBE patients;
DESCRIBE doctors;
DESCRIBE appointments;
DESCRIBE treatments;
DESCRIBE billing;

SELECT COUNT(*) FROM patients;
SELECT COUNT(*) FROM doctors;
SELECT COUNT(*) FROM appointments;
SELECT COUNT(*) FROM treatments;
SELECT COUNT(*) FROM billing;





-- Q1: Total Number of Patients


SELECT COUNT(*) AS total_patients
FROM patients;


-- Q2: Total Number of Doctors


SELECT COUNT(*) AS total_doctors
FROM doctors;


-- Q3: Total Number of Appointments


SELECT COUNT(*) AS total_appointments
FROM appointments;


-- Q4: Total Revenue Generated


SELECT SUM(amount) AS total_revenue
FROM billing;



-- Q5: Most Visited Doctor


SELECT 
    d.first_name,
    d.last_name,
    COUNT(a.appointment_id) AS total_visits
FROM appointments a
JOIN doctors d 
ON a.doctor_id = d.doctor_id
GROUP BY d.first_name, d.last_name
ORDER BY total_visits DESC
LIMIT 1;



-- Q6: Most Common Treatment Type


SELECT 
    treatment_type,
    COUNT(*) AS total_treatments
FROM treatments
GROUP BY treatment_type
ORDER BY total_treatments DESC
LIMIT 1;



-- Q7: Revenue Generated by Each Treatment Type


SELECT 
    t.treatment_type,
    SUM(b.amount) AS total_revenue
FROM billing b
JOIN treatments t 
ON b.treatment_id = t.treatment_id
GROUP BY t.treatment_type
ORDER BY total_revenue DESC;



-- Q8: Top 3 Revenue Generating Doctors


SELECT 
    d.first_name,
    d.last_name,
    SUM(b.amount) AS total_revenue
FROM billing b
JOIN treatments t 
ON b.treatment_id = t.treatment_id
JOIN appointments a 
ON t.appointment_id = a.appointment_id
JOIN doctors d 
ON a.doctor_id = d.doctor_id
GROUP BY d.first_name, d.last_name
ORDER BY total_revenue DESC
LIMIT 3;



-- Q9: Average Billing Amount


SELECT 
    AVG(amount) AS average_bill_amount
FROM billing;




-- Q10: Appointment Distribution by Status

SELECT 
    status,
    COUNT(*) AS total_appointments
FROM appointments
GROUP BY status;



-- Q11: Monthly Revenue Trend


SELECT 
    MONTH(bill_date) AS month,
    SUM(amount) AS monthly_revenue
FROM billing
GROUP BY MONTH(bill_date)
ORDER BY month;



-- Q12: Rank Doctors Based on Revenue


SELECT 
    d.first_name,
    d.last_name,
    SUM(b.amount) AS total_revenue,
    RANK() OVER (ORDER BY SUM(b.amount) DESC) AS revenue_rank
FROM billing b
JOIN treatments t 
ON b.treatment_id = t.treatment_id
JOIN appointments a 
ON t.appointment_id = a.appointment_id
JOIN doctors d 
ON a.doctor_id = d.doctor_id
GROUP BY d.first_name, d.last_name;



 -- Q13: How many male and female patients are there?
SELECT gender, COUNT(*) AS total_patients
FROM patients
GROUP BY gender;



 -- Q14: How many doctors are there in each specialization?
SELECT specialization, COUNT(*) AS total_doctors
FROM doctors
GROUP BY specialization;



 -- Q15: How many appointments are completed, cancelled, or pending?
SELECT status, COUNT(*) AS total
FROM appointments
GROUP BY status;



 -- Q16: What is the maximum billing amount?
SELECT MAX(amount) AS highest_bill
FROM billing;




 -- Q17: What is the minimum billing amount?
SELECT MIN(amount) AS lowest_bill
FROM billing;



-- Q18: How many treatments were done on each date?
SELECT treatment_date, COUNT(*) AS total_treatments
FROM treatments
GROUP BY treatment_date;




 -- Q 19: How many patients registered each month?
SELECT MONTH(registration_date) AS month,
       COUNT(*) AS total_patients
FROM patients
GROUP BY MONTH(registration_date)
ORDER BY month;




 -- Q20: List all doctors with more than 5 years of experience
SELECT first_name, last_name, years_experience
FROM doctors
WHERE years_experience > 5;





-- View Example
CREATE VIEW doctor_revenue AS
SELECT d.first_name, d.last_name, SUM(b.amount) AS total_revenue
FROM billing b
JOIN treatments t ON b.treatment_id = t.treatment_id
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN doctors d ON a.doctor_id = d.doctor_id
GROUP BY d.first_name, d.last_name;








